In [ ]:
# Import the numpy and pandas packages
import numpy as np
import pandas as pd

# Step 0: Load the dataset in the working folder

In [ ]:
# Unzip the zip file containing the data. Be sure to specify the correct path to the zip file
# The path below is specific to my own Google Drive. 
!unzip /content/drive/Othercomputers/My\ Mac/Documents/WSU/movies_data.zip

In [ ]:
# list the contents of the Present Working Directory (also called pwd)
!ls

# Step 1: Reading and Inspection



### Import and read

Import and read the movie database. Store it in a variable called `movies`.

In [ ]:
movies = pd.DataFrame(pd.read_csv("./MovieAssignmentData.csv")) # pd.read_csv function is used to read the data
movies.head() # notice the use of the .head() function for quickly displaying the data to get a feel

### Inspect the dataframe

Inspect the dataframe's columns, shapes, variable types etc.

In [ ]:
# Row, columns in the Data
movies.shape

In [ ]:
# Concise summary of the Dataframe.
movies.info()

**How many null values does the column with gross budget of the movie (by the name `gross`) have?** [5]

In [ ]:
# Generate descriptive statistics that summarize the central tendency, dispersion and shape of a datasetâ€™s distribution,
# excluding NaN values
movies.describe()

**What is the longest duration of any movie in the dataset?** [5]

In [ ]:
movies.director_name.describe()

**How many directors are there?** [5]

In [ ]:
# TODO [1 line]: Write code to find how many different movie genres there are [10]

**How many different movie genres are there?** [5]

In [ ]:
# TODO [1 line]: Write code to find number of languages across all the movies in the dataset [10]

**What is the number of different languages for the movies in the dataset?** [5]

# Step 2: Cleaning the Data

### Inspect Null values

Find out the number of Null values in all the columns and rows. Also, find the percentage of Null values in each column.

In [ ]:
# Code for column-wise null count here
movies.isnull().sum()

In [ ]:
# TODO [1 line]: Write your code for row-wise null count here; 
# Use the .sum() function, paying attention to the axis argument [10]

In [ ]:
# TODO [1-2 lines]: Write your code for column-wise null percentages here rounded to 2 decimal places [10]

### Fill NaN values
You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

In [ ]:
# TODO [2 lines]: Fill the NaN values in the 'language' column here with 'English'; use the .fillna() function [20]

In [ ]:
movies.language.isnull().sum() # this should print 0 if your code above is correct

### Drop unecessary rows
Some of the rows might have greater than five NaN values. Such rows aren't of much use for the analysis and hence, we can safely remove them

In [ ]:
# TODO [1 line]: Write your code for dropping these rows here that have > 5 NaN values [10]

### Check the number of retained rows
You might notice that two of the columns viz. `num_critic_for_reviews` and `actor_1_name` have small percentages of NaN values left. You can let these columns as it is for now. Check the number and percentage of the rows retained after completing all the tasks above.

In [ ]:
# TODO [1 line]: Write your code for checking the fraction of retained rows here [10]

### Count duplicate data entries
Count the number of duplicate rows. Use the `.drop_diplicates()` function of pandas

In [ ]:
len(movies)-len(movies.drop_duplicates())

In [ ]:
# TODO [1 line]: Write your code for dropping duplicate values here [10]

# Step 3: Data Analysis

### Find the movies with highest profit

- Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
- Sort the dataframe using the `profit` column as reference.
- Extract the top ten profiting movies in descending order and store them in a new dataframe called `top10`

In [ ]:
# TODO [1 line]: Write your code for creating the profit column here [10]

In [ ]:
# TODO [1 line]: Write your code for sorting the dataframe here [10]

In [ ]:
# print the top 10 movies data
top10 = movies_by_profit.head(10)
top10

### Find IMDb Top 250 Movies

- Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Ensure that for each of these movies, the `num_voted_users` is greater than 25,000.
Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.

In [ ]:
# TODO [3 lines]: Write your code for extracting the top 250 movies as per the IMDb score here. Make sure that you store it in a new dataframe 
# and name that dataframe as 'IMDb_Top_250' [30]

In [ ]:
# print a sample of the dataset
IMDb_Top_250

Extract all the movies in the `IMDb_Top_250` dataframe which are not in the English language and store them in a new dataframe named `Top_Foreign_Lang_Film`.

In [ ]:
# TODO [1 line]: Write code to do the above  [20]

In [ ]:
# print the top 5 foreign language films
Top_Foreign_Lang_Film.head()['movie_title']